--技能预警缓存

HealerEngineAlertSpellSingleCache = {
	--{Name = "寒冰箭", ID = 13322, Type = "Normal", Breakout = true, Instance = "艾尔文森林-流浪巫师-测试"}, 
	--{Name = "回音冲击波", ID = 81072, Type = "Normal", Breakout = true, Instance = "菲拉斯-加德米尔噩梦龙人-测试"}, 
	--{Name = "渗漏之雾", ID = 81074, Type = "Normal", Breakout = true, Instance = "菲拉斯-加德米尔噩梦龙人-测试"}, 
	-- {Name = "黑暗鞭笞", ID = 193211, Type = "Normal", Breakout = true, Instance = "噬魂之喉"}, 
	-- {Name = "剑刃奔涌", ID = 209602, Type = "Normal", Breakout = true, Instance = "群星庭院"}, 
	-- {Name = "光明之盾", ID = 192018, Type = "Normal", Breakout = true, Instance = "英灵殿"}, 
	-- {Name = "狂野之剑", ID = 193668, Type = "Normal", Breakout = true, Instance = "英灵殿"}, 
	-- {Name = "复仇之剪", ID = 197418, Type = "Normal", Breakout = true, Instance = "黑鸦堡垒"}, 
	-- {Name = "共受苦难", ID = 228852, Type = "Normal", Breakout = true, Instance = "卡拉赞"}, 
	-- {Name = "致死打击", ID = 227493, Type = "Normal", Breakout = true, Instance = "卡拉赞"}, 
	-- {Name = "穿刺飞弹", ID = 227628, Type = "Normal", Breakout = true, Instance = "卡拉赞"}, 
	-- {Name = "净化冲击波", ID = 334053, Type = "Normal", Breakout = true, Instance = "晋升高塔"}, 
	-- {Name = "严惩", ID = 322554, Type = "Normal", Breakout = true, Instance = "赤红深渊"}, 
	{Name = "深渊轰击", ID = 451119, Type = "Normal", Breakout = true, Instance = "破晨号-小怪"}, 
	{Name = "缠绕丝线", ID = 451099, Type = "Normal", Breakout = true, Instance = "破晨号-小怪"}, 
	{Name = "喷射丝线", ID = 434089, Type = "Normal", Breakout = true, Instance = "破晨号-拉夏南"}, 
	{Name = "暮光烈焰", ID = 451612, Type = "Normal", Breakout = true, Instance = "格瑞姆巴托-小怪"},
}
HealerEngineAlertSpellAOECache = {
	--{Name = "寒冰箭", ID = 13322, Type = "Normal", Breakout = true, Instance = "艾尔文森林-流浪巫师-测试"}, 
	--{Name = "回音冲击波", ID = 81072, Type = "Normal", Breakout = true, Instance = "菲拉斯-加德米尔噩梦龙人-测试"}, 
	--{Name = "渗漏之雾", ID = 81074, Type = "Normal", Breakout = true, Instance = "菲拉斯-加德米尔噩梦龙人-测试"}, 
	-- {Name = "北地冰风", ID = 193977, Type = "Normal", Type = "Normal", Breakout = true, Instance = "噬魂之喉"}, 
	-- {Name = "黑暗提灯", ID = 192019, Type = "Normal", Breakout = true, Instance = "噬魂之喉-小怪"}, 
	-- {Name = "碎裂", ID = 188114, Type = "Normal", Breakout = true, Instance = "奈萨里奥的巢穴"}, 
	-- {Name = "山崩", ID = 183088, Type = "Normal", Breakout = true, Instance = "奈萨里奥的巢穴"}, 
	-- {Name = "狂怒冲击", ID = 191823, Type = "Normal", Breakout = true, Instance = "守望者地窟"}, 
	-- {Name = "灼烧之雨", ID = 237565, Type = "Normal", Breakout = true, Instance = "永夜大教堂"}, 
	-- {Name = "粉碎之击", ID = 237276, Type = "Normal", Breakout = true, Instance = "永夜大教堂"}, 
	-- {Name = "炫目闪光", ID = 239232, Type = "Normal", Breakout = true, Instance = "永夜大教堂"}, 
	-- {Name = "聚焦毁灭", ID = 239235, Type = "Normal", Breakout = true, Instance = "永夜大教堂"}, 
	-- {Name = "邪能引爆", ID = 211464, Type = "Normal", Breakout = true, Instance = "群星庭院-小怪"}, 
	-- {Name = "切割漩涡", ID = 209676, Type = "Normal", Breakout = true, Instance = "群星庭院"}, 
	-- {Name = "凝聚闪电", ID = 193611, Type = "Normal", Breakout = true, Instance = "艾萨拉之眼"}, 
	-- {Name = "压抑深渊", ID = 197365, Type = "Normal", Breakout = true, Instance = "艾萨拉之眼"}, 
	-- {Name = "勇气号角", ID = 191284, Type = "Normal", Breakout = true, Instance = "英灵殿"}, 
	-- {Name = "风暴之眼", ID = 200901, Type = "Normal", Breakout = true, Instance = "英灵殿"}, 
	-- {Name = "邪恶重击", ID = 197810, Type = "Normal", Breakout = true, Instance = "魔法回廊"}, 
	-- {Name = "缠绕之网", ID = 200284, Type = "Normal", Breakout = true, Instance = "魔法回廊"}, 
	-- {Name = "镇压协议", ID = 196070, Type = "Normal", Breakout = true, Instance = "魔法回廊"}, 
	-- {Name = "力场炸弹", ID = 202974, Type = "Normal", Breakout = true, Instance = "魔法回廊"}, 
	-- {Name = "疯狂怒吼", ID = 200580, Type = "Normal", Breakout = true, Instance = "黑心林地-小怪"}, 
	-- {Name = "碎裂之土", ID = 204666, Type = "Repel", Breakout = true, Instance = "黑心林地"}, 
	-- {Name = "下冲气流", ID = 199345, Type = "Normal", Breakout = true, Instance = "黑心林地"}, 
	-- {Name = "弱肉强食", ID = 200238, Type = "Normal", Breakout = true, Instance = "黑心林地"}, 
	-- {Name = "灵魂爆发", ID = 196587, Type = "Normal", Breakout = true, Instance = "黑鸦堡垒"}, 
	-- {Name = "利刃之舞", ID = 200291, Type = "Normal", Breakout = true, Instance = "黑鸦堡垒"}, 
	-- {Name = "大地践踏", ID = 198073, Type = "Normal", Breakout = true, Instance = "黑鸦堡垒"}, 
	-- {Name = "针刺虫群", ID = 201733, Type = "Normal", Breakout = true, Instance = "黑鸦堡垒"}, 
	-- {Name = "群体忏悔", ID = 227508, Type = "Normal", Breakout = true, Instance = "卡拉赞"}, 
	-- {Name = "无尽寒冬", ID = 227779, Type = "Normal", Breakout = true, Instance = "卡拉赞"}, 
	-- {Name = "梦魇爆破", ID = 209471, Type = "Normal", Breakout = true, Instance = "翡翠梦魇"}, 
	-- {Name = "召云聚气", ID = 212707, Type = "Normal", Breakout = true, Instance = "翡翠梦魇"}, 
	-- {Name = "召云聚气", ID = 212709, Type = "Normal", Breakout = true, Instance = "翡翠梦魇"}, 
	-- {Name = "震耳喧嚣", ID = 197969, Type = "Normal", Breakout = true, Instance = "翡翠梦魇"}, 
	-- {Name = "腐蚀新星", ID = 207830, Type = "Normal", Breakout = true, Instance = "翡翠梦魇"}, 
	-- {Name = "腐蚀新星", ID = 225896, Type = "Normal", Breakout = true, Instance = "翡翠梦魇"}, 
	-- {Name = "勇气号角", ID = 228012, Type = "Normal", Breakout = true, Instance = "勇气试炼"}, 
	-- {Name = "神准冲击", ID = 227629, Type = "Normal", Breakout = true, Instance = "勇气试炼"}, 
	-- {Name = "势不可挡", ID = 211927, Type = "Normal", Breakout = true, Instance = "暗夜要塞"}, 
	-- {Name = "猛击", ID = 205862, Type = "Normal", Breakout = true, Instance = "暗夜要塞"}, 
	-- {Name = "见证虚空", ID = 207720, Type = "Normal", Breakout = true, Instance = "暗夜要塞"}, 
	-- {Name = "虚空新星", ID = 207439, Type = "Normal", Breakout = true, Instance = "暗夜要塞"}, 
	-- {Name = "碎裂星辰", ID = 233272, Type = "Normal", Breakout = true, Instance = "萨格拉斯之墓"}, 
	-- {Name = "地狱燃烧", ID = 233062, Type = "Normal", Breakout = true, Instance = "萨格拉斯之墓"}, 
	-- {Name = "不羁怒火", ID = 231854, Type = "Normal", Breakout = true, Instance = "萨格拉斯之墓"}, 
	-- {Name = "月蚀之拥", ID = 233263, Type = "Normal", Breakout = true, Instance = "萨格拉斯之墓"}, 
	-- {Name = "末日分裂", ID = 236544, Type = "Normal", Breakout = true, Instance = "萨格拉斯之墓"}, 
	-- {Name = "分裂末日", ID = 236542, Type = "Normal", Breakout = true, Instance = "萨格拉斯之墓"}, 
	-- {Name = "湮灭猛击", ID = 239439, Type = "Normal", Breakout = true, Instance = "萨格拉斯之墓"}, 
	-- {Name = "造物之锤", ID = 241635, Type = "Normal", Breakout = true, Instance = "萨格拉斯之墓"}, 
	-- {Name = "湮灭之锤", ID = 241636, Type = "Normal", Breakout = true, Instance = "萨格拉斯之墓"}, 
	-- {Name = "割裂现实", ID = 235572, Type = "Normal", Breakout = true, Instance = "萨格拉斯之墓"}, 
	-- {Name = "割裂现实", ID = 239132, Type = "Normal", Breakout = true, Instance = "萨格拉斯之墓"}, 
	-- {Name = "释放混沌", ID = 234059, Type = "Normal", Breakout = true, Instance = "萨格拉斯之墓"}, 
	-- {Name = "爆发恐惧烈焰", ID = 235120, Type = "Normal", Breakout = true, Instance = "萨格拉斯之墓"}, 
	-- {Name = "千魂之暗", ID = 238999, Type = "Normal", Breakout = true, Instance = "萨格拉斯之墓"}, 
	-- {Name = "根除", ID = 244969, Type = "Normal", Breakout = true, Instance = "安托鲁斯，燃烧王座"}, 
	-- {Name = "虹吸腐蚀", ID = 244056, Type = "Normal", Breakout = true, Instance = "安托鲁斯，燃烧王座"}, 
	-- {Name = "烈焰撕裂", ID = 245463, Type = "Normal", Breakout = true, Instance = "安托鲁斯，燃烧王座"},
	-- {Name = "痛苦之怒", ID = 257296, Type = "Normal", Breakout = true, Instance = "安托鲁斯，燃烧王座"}, 
	-- {Name = "溃烂收割", ID = 259732, Type = "Normal", Breakout = true, Instance = "地渊孢林"},
	-- {Name = "狂怒", ID = 333787, Type = "Normal", Breakout = true, Instance = "彼界-小怪"},
	-- {Name = "粉碎现实", ID = 326171, Type = "Normal", Breakout = true, Instance = "彼界-穆厄扎拉"},
	-- {Name = "灵魂风暴", ID = 330716, Type = "Normal", Breakout = true, Instance = "伤逝剧场-小怪"},
	-- {Name = "魔药践踏", ID = 324527, Type = "Repel", Breakout = true, Instance = "凋魂之殇-酤团"},
	-- {Name = "感染毒雨", ID = 322232, Type = "Normal", Breakout = true, Instance = "凋魂之殇-斯特拉达玛侯爵"},
	-- {Name = "痛击", ID = 326409, Type = "Normal", Breakout = true, Instance = "赎罪大厅-小怪"},
	-- {Name = "巨兽奔袭", ID = 319713, Type = "Normal", Breakout = true, Instance = "赤红深渊-贪食的克里克西斯"},
	-- {Name = "至高仪式", ID = 325360, Type = "Normal", Breakout = true, Instance = "赤红深渊-大学监贝律莉娅"},
	-- {Name = "深渊爆炸", ID = 334625, Type = "Normal", Breakout = true, Instance = "晋升高塔-疑虑圣杰德沃丝"},
	{Name = "地动咆哮", ID = 450454, Type = "Repel", Breakout = true, Instance = "卡兹阿加-欧尔塔，破碎山峦"},
	{Name = "虚空奔袭", ID = 451222, Type = "Normal", Breakout = true, Instance = "千丝之城-小怪"},
	{Name = "暮落", ID = 439692, Type = "Normal", Breakout = true, Instance = "千丝之城-女王之牙"},
	{Name = "霜凝匕首", ID = 440468, Type = "Normal", Breakout = true, Instance = "千丝之城-女王之牙"},
	{Name = "毒性喷吐", ID = 434137, Type = "Normal", Breakout = true, Instance = "千丝之城-小怪"},
	{Name = "凶暴践踏", ID = 436205, Type = "Normal", Breakout = true, Instance = "千丝之城-小怪"},
	{Name = "黏稠黑暗", ID = 441289, Type = "Repel", Breakout = true, Instance = "千丝之城-凝结聚合体"},
	{Name = "黑暗脉动", ID = 441395, Type = "Normal", Breakout = true, Instance = "千丝之城-凝结聚合体"},
	{Name = "晦幽纺纱", ID = 446717, Type = "Normal", Breakout = true, Instance = "千丝之城-小怪"},
	{Name = "震颤猛击", ID = 447271, Type = "Normal", Breakout = true, Instance = "千丝之城-小怪"},
	{Name = "捻接", ID = 439341, Type = "Normal", Breakout = true, Instance = "千丝之城-大捻接师艾佐"},
	{Name = "晦幽纺纱", ID = 438860, Type = "Normal", Breakout = true, Instance = "千丝之城-大捻接师艾佐"},
	{Name = "震颤猛击", ID = 437700, Type = "Normal", Breakout = true, Instance = "千丝之城-大捻接师艾佐"},
	{Name = "虚空暴发", ID = 426771, Type = "Normal", Breakout = true, Instance = "矶石宝库-小怪"},
	{Name = "大地破裂", ID = 424879, Type = "Normal", Breakout = true, Instance = "矶石宝库-E.D.N.A."},
	{Name = "排放口", ID = 445541, Type = "Normal", Breakout = true, Instance = "矶石宝库-机械大师"},
	{Name = "炽焰波峰", ID = 428519, Type = "Normal", Breakout = true, Instance = "矶石宝库-机械大师"},
	{Name = "炽焰波峰", ID = 428535, Type = "Normal", Breakout = true, Instance = "矶石宝库-机械大师"},
	{Name = "火成岩锤", ID = 428711, Type = "Normal", Breakout = true, Instance = "矶石宝库-机械大师"},
	{Name = "巨岩碾压", ID = 428879, Type = "Normal", Breakout = true, Instance = "矶石宝库-小怪"},
	{Name = "虚空释能", ID = 423324, Type = "Normal", Breakout = true, Instance = "矶石宝库-斯卡莫拉克"},
	{Name = "黑曜光束", ID = 453212, Type = "Normal", Breakout = true, Instance = "破晨号-代言人夏多克朗"},
	{Name = "晦影腐朽", ID = 451102, Type = "Normal", Breakout = true, Instance = "破晨号-小怪"},
	{Name = "晦影腐朽", ID = 426787, Type = "Normal", Breakout = true, Instance = "破晨号-阿努布伊卡基"},
	{Name = "折磨喷发", ID = 431349, Type = "Normal", Breakout = true, Instance = "破晨号-小怪"},
	{Name = "侵蚀喷涌", ID = 448888, Type = "Normal", Breakout = true, Instance = "破晨号-拉夏南"},
	{Name = "蛛纱强袭", ID = 438473, Type = "Normal", Breakout = true, Instance = "艾拉-卡拉，回响之城-阿瓦诺克斯"},
	{Name = "警示尖鸣", ID = 438476, Type = "Normal", Breakout = true, Instance = "艾拉-卡拉，回响之城-阿瓦诺克斯"},
	{Name = "猛击", ID = 465012, Type = "Normal", Breakout = true, Instance = "艾拉-卡拉，回响之城-小怪"},
	{Name = "野蛮猛击", ID = 434252, Type = "Repel", Breakout = true, Instance = "艾拉-卡拉，回响之城-小怪"},
	{Name = "命令咆哮", ID = 448847, Type = "Normal", Breakout = true, Instance = "格瑞姆巴托-乌比斯将军"},
	{Name = "熔岩觉醒", ID = 451965, Type = "Normal", Breakout = true, Instance = "格瑞姆巴托-小怪"},
	{Name = "晦暗之风", ID = 451939, Type = "Repel", Breakout = true, Instance = "格瑞姆巴托-小怪"},
	{Name = "铸造利斧", ID = 451996, Type = "Normal", Breakout = true, Instance = "格瑞姆巴托-铸炉之主索朗格斯"},
	{Name = "铸造利剑", ID = 456902, Type = "Normal", Breakout = true, Instance = "格瑞姆巴托-铸炉之主索朗格斯"},
	{Name = "铸造战锤", ID = 456900, Type = "Normal", Breakout = true, Instance = "格瑞姆巴托-铸炉之主索朗格斯"},
	{Name = "熔火乱舞", ID = 449444, Type = "Normal", Breakout = true, Instance = "格瑞姆巴托-铸炉之主索朗格斯"},
	{Name = "扬升", ID = 451387, Type = "Normal", Breakout = true, Instance = "格瑞姆巴托-小怪"},
	{Name = "黑暗喷发", ID = 456713, Type = "Normal", Breakout = true, Instance = "格瑞姆巴托-小怪"},
	{Name = "暮光打击", ID = 456751, Type = "Repel", Breakout = true, Instance = "格瑞姆巴托-达加·燃影者"},
	{Name = "虚空涌动", ID = 450077, Type = "Normal", Breakout = true, Instance = "格瑞姆巴托-埃鲁达克，地狱公爵"},
	{Name = "深渊腐蚀", ID = 448057, Type = "Normal", Breakout = true, Instance = "格瑞姆巴托-埃鲁达克，地狱公爵"}, 
	{Name = "炽烈弹射", ID = 463182, Type = "Normal", Breakout = true, Instance = "围攻伯拉勒斯-恐怖船长洛克伍德"}, 
	{Name = "碾压重击", ID = 272711, Type = "Normal", Breakout = true, Instance = "围攻伯拉勒斯-小怪"}, 
	{Name = "激流破奔", ID = 257882, Type = "Normal", Breakout = true, Instance = "围攻伯拉勒斯-哈达尔·黑渊"}, 
	{Name = "愤怒鞭笞", ID = 324909, Type = "Normal", Breakout = true, Instance = "塞兹仙林的迷雾-小怪"}, 
	{Name = "酸性新星", ID = 460092, Type = "Normal", Breakout = true, Instance = "塞兹仙林的迷雾-小怪"}, 
}